In [48]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

In [49]:
df = pd.read_csv("bank-additional-full.csv",sep=';')

In [50]:
df.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             41188 non-null  int64
 1   job             41188 non-null  object
 2   marital         41188 non-null  object
 3   education       41188 non-null  object
 4   default         41188 non-null  object
 5   housing         41188 non-null  object
 6   loan            41188 non-null  object
 7   contact         41188 non-null  object
 8   month           41188 non-null  object
 9   day_of_week     41188 non-null  object
 10  duration        41188 non-null  int64
 11  campaign        41188 non-null  int64
 12  pdays           41188 non-null  int64
 13  previous        41188 non-null  int64
 14  poutcome        41188 non-null  object
 15  emp.var.rate    41188 non-null  float64
 16  cons.price.idx  41188 non-null  float64
 17  cons.conf.idx   41188 non-null  float64
 18  euribor3m       41188 non-null  float64
 19  nr.employed     41188 non-null  float64
 20  y               41188 non-null  object
dtypes: float64(5), int64(5), object(11)
memory usage: 6.6+ MB

In [52]:
df.describe()

,age,duration,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed
count,41188.00000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000
mean,40.02406,258.285010,2.567593,962.475454,0.172963,0.081886,93.575664,-40.502600,3.621291,5167.035911
std,10.42125,259.279249,2.770014,186.910907,0.494901,1.570960,0.578840,4.628198,1.734447,72.251528
min,17.00000,0.000000,1.000000,0.000000,0.000000,-3.400000,92.201000,-50.800000,0.634000,4963.600000
25%,32.00000,102.000000,1.000000,999.000000,0.000000,-1.800000,93.075000,-42.700000,1.344000,5099.100000
50%,38.00000,180.000000,2.000000,999.000000,0.000000,1.100000,93.749000,-41.800000,4.857000,5191.000000
75%,47.00000,319.000000,3.000000,999.000000,0.000000,1.400000,93.994000,-36.400000,4.961000,5228.100000
max,98.00000,4918.000000,56.000000,999.000000,7.000000,1.400000,94.767000,-26.900000,5.045000,5228.100000

In [53]:
df['y'].value_counts()

y
no     36548
yes     4640
Name: count, dtype: int64

In [54]:
y = {"no": 0, "yes": 1}
df["y"] = df["y"].map(y)

In [55]:
df['y'].value_counts()

y
0    36548
1     4640
Name: count, dtype: int64

In [56]:
numeric_df = df.select_dtypes(include=['int64', 'float64'])
X = numeric_df.drop("y", axis=1).values
y = numeric_df["y"].values.reshape(-1, 1)

In [57]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [58]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [59]:
n_features = X_train.shape[1]
W = np.zeros((n_features, 1))
b = 0

learning_rate = 0.01
epochs = 2000

In [68]:
for i in range(epochs):

 
    z = np.dot(X_train, W) + b
    y_pred = sigmoid(z)

  
    cost = -np.mean(
        y_train * np.log(y_pred + 1e-9) +
        (1 - y_train) * np.log(1 - y_pred + 1e-9)
    )


    dz = y_pred - y_train
    dW = np.dot(X_train.T, dz) / len(X_train)
    db = np.sum(dz) / len(X_train)

  
    W -= learning_rate * dW
    b -= learning_rate * db

    if i % 200 == 0:
        print(f"Epoch {i}, Cost = {cost}")

C:\Users\srisu\AppData\Local\Temp\ipykernel_25128\1702624272.py:2: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))

Epoch 0, Cost = 2.0707303431150654
Epoch 200, Cost = 2.298112696173946
Epoch 400, Cost = 2.266666162276445
Epoch 600, Cost = 2.3301881607478436
Epoch 800, Cost = 2.3301881607478436
Epoch 1000, Cost = 8.823056342943145
Epoch 1200, Cost = 2.076389231595422
Epoch 1400, Cost = 2.030773820407528
Epoch 1600, Cost = 6.986368783128926
Epoch 1800, Cost = 2.058568096875189

In [69]:
y_pred_test = sigmoid(np.dot(X_test, W) + b)
y_pred_class = (y_pred_test >= 0.5)

C:\Users\srisu\AppData\Local\Temp\ipykernel_25128\1702624272.py:2: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))

In [70]:
accuracy = np.mean(y_pred_class == y_test)
print("Accuracy:", accuracy)

Accuracy: 0.8504491381403253